typography_spectrum: 0.30576
color:
  brandColors:
    - '#f1dfea'
    - '#005611'
    - '#020e0c'
    - '#008721'
    - '#97c16f'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Seth McAllister
  email: ''
name: Beautiful Norikura
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Instagram
    url: instagram.com/beautifulnorikura
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Beautiful Norikura
description: Explore the Beauty of the Japanese Alps
purpose: []
