name: '#BeautifulNorikura'
favicon: null
layout_spectrum: 0.8028674
typography_spectrum: 0.4677419
title: '#BeautifulNorikura'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#c7cbd4'
    - '#869bba'
    - '#b63935'
    - '#3b8a39'
  brandStrength: 1
  lightness: 0.7275985
  saturation: 0.9863346
  rhythmicContrast: 0.6698805
purpose: []
