name: '#BeautifulNorikura'
favicon: null
layout_spectrum: 0.8028674
typography_spectrum: 0.4677419
title: '#BeautifulNorikura'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7deca'
    - '#b7bbc7'
    - '#1f282f'
    - '#6f5f50'
    - '#9b8173'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
